### ISSUE TITLE
[Bug] Fail to start/initialise in Safari on iOS 5.1.1 (iPad1) 

### ISSUE THREAD

**Issue by crgmrgn** [gabrielecirulli/2048#47]
Board and webpage draw correctly, but both initial tiles do not display and hence the game cannot be started.

Enabling debug to the console for Safari reports two issues:
- HTML: Error line 14 "Viewport argument key "target-densitydpi" not recognized and ignored
- Javascript: Error undefined TypeError: 'undefined' is not a function

Works fine on a later iOS release (7.1), but this older iPad is effectively orphaned on 5.1.1 as the last available OS :)
